FROM php:8.1-fpm

RUN apt-get update && apt-get install -y \
    git \
    curl \
    wget \
    libyaml-dev \
    zip \
    unzip

# Clear cache
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# Install xdebug
RUN pecl install xdebug-3.1.0 && docker-php-ext-enable xdebug

# Install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Add user for application
RUN mkdir /data
RUN groupadd -g 1000 www
RUN useradd -u 1000 -ms /bin/bash -g www www && chown www:www /data

# Change current user to www
USER www

WORKDIR /data
# COPY ./src/ /var/www/html
COPY --chown=www:www . /data


EXPOSE 9000
CMD ["php-fpm"]
